# Generated by Django 5.0.4 on 2024-05-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniachievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name': 'Выпускники', 'verbose_name_plural': 'Выпускники'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'verbose_name': 'Совет', 'verbose_name_plural': 'Советы'},
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='content',
            new_name='tip',
        ),
    ]
